In [2]:
import numpy as np
import pandas as pd
import re
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors as pltcol
from scipy import stats
import math
from scipy.stats import mannwhitneyu
import glob

In [3]:
genome = pd.read_csv('aa_seq_wuhan.csv', sep=',')
genome

,name1,name2,start,end,seq,name3
0,nsp1,leader,266,805,MESLVPGFNEKTHVQLSLPVLQVRDVLVRGFGDSVEEVLSEARQHL...,leader
1,nsp2,_,806,2719,AYTRYVDNNFCGPDGYPLECIKDLLARAGKASCTLSEQLDFIDTKR...,nsp2
2,nsp3,_,2720,8554,APTKVTFGDDTVIEVQGYKSVNITFELDERIDKVLNEKCSAYTVEL...,nsp3
3,nsp4,_,8555,10054,KIVNNWLKQLIKVTLVFLFVAAIFYLITPVHVMSKHTDFSSEIIGY...,nsp4
4,nsp5,3C,10055,10972,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,3C
5,nsp6,_,10973,11842,SAVKRTIKGTHHWLLLTILTSLLVLVQSTQWSLFFFLYENAFLPFA...,nsp6
6,nsp7,_,11843,12091,SKMSDVKCTSVVLLSVLQQLRVESSSKLWAQCVQLHNDILLAKDTT...,nsp7
7,nsp8,_,12092,12685,AIASEFSSLPSYAAFATAQEAYEQAVANGDSEVVLKKLKKSLNVAK...,nsp8
8,nsp9,_,12686,13024,NNELSPVALRQMSCAAGTTQTACTDDNALAYYNTTKGGRFVLALLS...,nsp9
9,nsp10,_,13025,13441,AGNATEVPANSTVLSFCAFAVDAAKAYKDYLASGGQPITNCVKMLC...,nsp10
10,nsp11,_,13442,13480,SADAQSFLNGFAV,nsp11
11,nsp12,RdRp,13442:13468,13468:16236,SADAQSFLNRVCGVSAARLTPCGTGTSTDVVYRAFDIYNDKVAGFA...,RdRp
12,nsp13,helicase,16237,18039,AVGACVLCNSQTSLRCGACIRRPFLCCKCCYDHVISTSHKLVLSVN...,helicase
13,nsp14,exonuclease,18040,19620,AENVTGLFKDCSKVITGLHPTQAPTHLSVDTKFKTEGLCVDIPGIP...,exonuclease
14,nsp15,endornase,19621,20658,SLENVAFNVVNKGHFDGQQGEVPVSIINNTVYTKVDGVDVELFENK...,endornase
15,nsp16,methyltransferase,20659,21552,SSQAWQPGVAMPNLYKMQRMLLEKCDLQNYGDSATLPKGIMMNVAK...,methyltransferase
16,S,spike,21563,25384,MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSS...,Spike
17,ns3,ORF3a,25393,26220,MDLFMRIFTIGTVTLKQGEIKDATPSDFVRATATIPIQASLPFGWL...,ORF3a
18,E,_,26245,26472,MYSFVSEETGTLIVNSVLLFLAFVVFLLVTLAILTALRLCAYCCNI...,E
19,M,_,26523,27191,MADSNGTITVEELKKLLEQWNLVIGFLFLTWICLLQFAYANRNRFL...,M
20,ns6,ORF6,27202,27387,MFHLVDFQVTIAEILLIIMRTFKVSIWNLDYIINLIIKNLSKSLTE...,ORF6
21,ns7a,ORF7a,27394,27759,MKIILFLALITLATCELYHYQECVRGTTVLLKEPCSSGTYEGNSPF...,ORF7a
22,ns7b,ORF7b,27756,27887,MIELSLIDFYLCFLAFLLFLVLIMLIIFWFSLELQDHNETCHA,ORF7b
23,ns8,ORF8,27894,28259,MKFLVFLGIITTVAAFHQECSLQSCTQHQPYVVDDPCPIHFYSKWY...,ORF8
24,N,_,28274,29533,MSDNGPQNQRNAPRITFGGPSDSTGSNQNGERSGARSKQRRPQGLP...,N
25,ns10,ORF10,29558,29674,MGYINVFAFPFTIYSLLLCRMNSRNYIAQVDVVNFNLT,ORF10

In [4]:
genome = pd.read_csv('aa_seq_wuhan.csv', sep=',')
steps = [8,9,10,11,12]
peptides_wt = {}
peptides_only = {}
for pr in genome['name3']:
    coord_start = []
    coord_end = []
    peptides = []
    Len = []
    seq = genome[genome['name3'] == pr]['seq'].values[0]
    #print(pr, seq)
    for i in range(len(seq)-8+1):
        for step in steps:
            if i + step <= len(seq):
                #print(seq, type(seq), 'len', len(seq))
                #coord = np.arange(start=i, stop=i + step-1, 1)
                coord_start.append(i + 1)
                coord_end.append(i+step)
                peptides.append(seq[i:i+step])
                Len.append(step)
    peptides_wt[pr] = pd.DataFrame({'Length': Len, 'Coordinates start': coord_start, 'Coordinates end': coord_end, 'Peptides': peptides})
    peptides_only[pr] = peptides
prot_name = []
pept = []
for key in peptides_only.keys():
    #print(peptides_only[key])
    prot_name += [key for i in range(len(peptides_only[key]))]
    pept += peptides_only[key]
df_pept = pd.DataFrame({'prot_name':prot_name, 'peptide':pept})

df_coord = pd.concat(peptides_wt).reset_index()
df_coord= df_coord.drop(columns = {'level_1'})
df_coord= df_coord.rename(columns = {'level_0':'prot_name', 'Peptides':'peptide'})
df_wuhan = pd.merge(df_pept, df_coord, on=['prot_name', 'peptide'])

genome = pd.read_csv('omicron_sequences.csv', sep='\t')
steps = [8,9,10,11,12]
peptides_wt = {}
peptides_only = {}
for pr in genome['name3']:
    coord_start = []
    coord_end = []
    peptides = []
    Len = []
    seq = genome[genome['name3'] == pr]['omicron_seq'].values[0]
    #print(pr, seq)
    for i in range(len(seq)-8+1):
        for step in steps:
            if i + step <= len(seq):
                #print(seq, type(seq), 'len', len(seq))
                #coord = np.arange(start=i, stop=i + step-1, 1)
                coord_start.append(i + 1)
                coord_end.append(i+step)
                peptides.append(seq[i:i+step])
                Len.append(step)
    peptides_wt[pr] = pd.DataFrame({'Length': Len, 'Coordinates start': coord_start, 'Coordinates end': coord_end, 'Peptides': peptides})
    peptides_only[pr] = peptides
prot_name = []
pept = []
for key in peptides_only.keys():
    #print(peptides_only[key])
    prot_name += [key for i in range(len(peptides_only[key]))]
    pept += peptides_only[key]
df_pept = pd.DataFrame({'prot_name':prot_name, 'peptide':pept})
df_coord = pd.concat(peptides_wt).reset_index()
df_coord= df_coord.drop(columns = {'level_1'})
df_coord= df_coord.rename(columns = {'level_0':'prot_name', 'Peptides':'peptide'})
df_om = pd.merge(df_pept, df_coord, on=['prot_name', 'peptide'])

genome = pd.read_csv('delta_sequences.csv', sep='\t')
steps = [8,9,10,11,12]
peptides_wt = {}
peptides_only = {}
for pr in genome['name3']:
    coord_start = []
    coord_end = []
    peptides = []
    Len = []
    seq = genome[genome['name3'] == pr]['delta_seq'].values[0]
    #print(pr, seq)
    for i in range(len(seq)-8+1):
        for step in steps:
            if i + step <= len(seq):
                #print(seq, type(seq), 'len', len(seq))
                #coord = np.arange(start=i, stop=i + step-1, 1)
                coord_start.append(i + 1)
                coord_end.append(i+step)
                peptides.append(seq[i:i+step])
                Len.append(step)
    peptides_wt[pr] = pd.DataFrame({'Length': Len, 'Coordinates start': coord_start, 'Coordinates end': coord_end, 'Peptides': peptides})
    peptides_only[pr] = peptides
prot_name = []
pept = []
for key in peptides_only.keys():
    #print(peptides_only[key])
    prot_name += [key for i in range(len(peptides_only[key]))]
    pept += peptides_only[key]
df_pept = pd.DataFrame({'prot_name':prot_name, 'peptide':pept})
df_coord = pd.concat(peptides_wt).reset_index()
df_coord= df_coord.drop(columns = {'level_1'})
df_coord= df_coord.rename(columns = {'level_0':'prot_name', 'Peptides':'peptide'})
df_d = pd.merge(df_pept, df_coord, on=['prot_name', 'peptide'])
df = pd.concat([df_d, df_om, df_wuhan]).drop_duplicates('peptide')

In [5]:
immun1 = pd.read_csv('tcell_table_export_1701167238.csv', header=[0,1])
immun2 = pd.read_csv('tcell_table_export_1701167293.csv', header=[0,1])
immun3 = pd.read_csv('tcell_table_export_1701167144.csv', header=[0,1])
immun_I = pd.concat([immun1, immun2, immun3])
immun_I.columns = [c[0] + "_" + c[1] for c in immun_I.columns]
immun_I = immun_I[['Epitope_Name', 'MHC Restriction_Name']].drop_duplicates().rename(columns = {'Epitope_Name':
                                                'peptide', 'MHC Restriction_Name':'Allele Name'})[['peptide','Allele Name']]

immun_I = immun_I[(immun_I['peptide'].str.len() <13) & (immun_I['peptide'].str.len() >7)&(immun_I['Allele Name'].str.contains(':'))]
immun_I = immun_I.fillna(0)
immun_I = immun_I[(~immun_I['Allele Name'].str.startswith('HLA-D'))].drop_duplicates()
immun_I['Allele Name'] = immun_I['Allele Name'].str.replace('*', '')
immun_I_orig = immun_I
immun_I_orig

C:\Users\Lenovo ThinkPad\AppData\Local\Temp\ipykernel_19956\1517793800.py:1: DtypeWarning: Columns (13,14,61,62,63,64,69,73,74,75,92,105,115) have mixed types. Specify dtype option on import or set low_memory=False.
  immun1 = pd.read_csv('tcell_table_export_1701167238.csv', header=[0,1])
C:\Users\Lenovo ThinkPad\AppData\Local\Temp\ipykernel_19956\1517793800.py:2: DtypeWarning: Columns (13,14,61,62,63,64,69,73,74,75,92,105,115) have mixed types. Specify dtype option on import or set low_memory=False.
  immun2 = pd.read_csv('tcell_table_export_1701167293.csv', header=[0,1])
C:\Users\Lenovo ThinkPad\AppData\Local\Temp\ipykernel_19956\1517793800.py:3: DtypeWarning: Columns (13,14,61,62,63,64,69,73,74,75,92,105,115) have mixed types. Specify dtype option on import or set low_memory=False.
  immun3 = pd.read_csv('tcell_table_export_1701167144.csv', header=[0,1])
C:\Users\Lenovo ThinkPad\AppData\Local\Temp\ipykernel_19956\1517793800.py:14: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  immun_I['Allele Name'] = immun_I['Allele Name'].str.replace('*', '')

          peptide Allele Name
682      FLAFVVFL  HLA-A02:01
683     FLFLTWICL  HLA-A02:01
684     KLDDKDPNF  HLA-A02:01
685    YLGTGPEAGL  HLA-A02:01
686     LLLDRLNQL  HLA-A02:01
...           ...         ...
5672   ALLTLQQIEL  HLA-A02:01
5673   FCLEASFNYL  HLA-A02:01
5674  FLTENLLLYID  HLA-A02:01
5675    GLVAEWFLA  HLA-A02:01
5676  YVNTFSSTFNV  HLA-A02:01

[1953 rows x 2 columns]

In [6]:
df_immune = pd.merge(df, immun_I_orig, on = 'peptide')
df_galka = df_immune.drop_duplicates(['prot_name', 'Coordinates start', 'Coordinates end'])
df_galka

,prot_name,peptide,Length,Coordinates start,Coordinates end,Allele Name
0,leader,VLQVRDVLV,9,20,28,HLA-A02:01
1,leader,VLSEARQHL,9,38,46,HLA-A02:01
2,leader,HLKDGTCGL,9,45,53,HLA-B08:01
3,leader,GLVEVEKGV,9,52,60,HLA-A02:01
4,leader,APHGHVMVEL,10,79,88,HLA-B07:02
...,...,...,...,...,...,...
1758,ORF7b,LIDFYLCFL,9,6,14,HLA-A02:01
1759,ORF7b,AFLLFLVLI,9,15,23,HLA-A01:01
1760,ORF7b,LLFLVLIML,9,17,25,HLA-A02:01
1761,ORF7b,IIFWFSLE,8,26,33,HLA-A02:01
1762,ORF7b,IIFWFSLEL,9,26,34,HLA-A02:01

In [ ]:
df_immune = pd.merge(df, immun_I_orig, on = 'peptide')
df_immune.to_csv('immun_epit_all3_HLA.csv', sep = '\t', index = False)

df_immune = pd.merge(df_wuhan, immun_I_orig, on = 'peptide')
df_immune.to_csv('immun_epit_all3_HLA_Wuhan.csv', sep = '\t', index = False) #for immunocompromised patients - only Wuhan epitopes


df_galka = df_immune.drop_duplicates(['prot_name', 'Coordinates start', 'Coordinates end'])
df_galka.to_csv('immun_epit_all3.csv', sep = '\t', index = False)
#that is the file with immunogenic epitopes. It is ised to obtain mutations from the GISAID

In [ ]:
#script to collect individual mutations from GISAID 
import re
import optparse
from collections import defaultdict
import itertools
import random
import copy
import sys

parser=optparse.OptionParser()
parser.add_option('-p', '--paths', help='', type='str')
options, args=parser.parse_args()

paths = options.paths
voc_lineage = paths.replace(".paths.tsv","")

prot_begins = ["266","806","2720","8555","10055","10973","11843","12092","12686","13025","16237","18040","19621","20659","21563","25393","26245","26523","27202","27394","27756","27894","28274","29558"]
prot_begins = [eval(i) for i in prot_begins]
#print(type(prot_begins))
prot_ends = ["805","2719","8554","10054","10972","11842","12091","12685","13024","13441","18039","19620","20658","21552","25384","26220","26472","27191","27387","27759","27887","28259","29533","29674"]
prot_ends = [eval(i) for i in prot_ends]
#print(type(prot_ends))
prot_names = ["leader","nsp2","nsp3","nsp4","3C","nsp6","nsp7","nsp8","nsp9","nsp10","helicase","exonuclease","endornase","methyltransferase","spike","ORF3a","E","M","ORF6","ORF7a","ORF7b","ORF8","N","ORF10"]

codon_aa = dict()
with open("genetic_code") as codon_table:
    for line in codon_table:
        codon = line.split(" ")[0]
        aa = line.split(" ")[1]
        codon_aa[codon] = aa

ref_file_lineage = open('OmicronReference.fasta', 'r')
firstLine = ref_file_lineage.readline()
refseq_lineage = ref_file_lineage.readline().rstrip()

protpos_ref = dict()
ref_file = open('/gss/home/e.riumina/Galya_Guest/ReferenceWuhan.one_line.fasta', 'r')
firstLine = ref_file.readline()
refseq = ref_file.readline().rstrip()
for k in range(1,len(refseq)+1):
    nt = refseq[(k-1)]
    k = int(k)
    protpos_ref[k] = nt
    #print(str(k)+"\t"+str(nt))


prot_mut_month_times = defaultdict(lambda: defaultdict(int))
prot_pos_month_times = defaultdict(lambda: defaultdict(int))
with open(options.paths) as mut_file:
    for line in mut_file:
        protpos_nt = copy.deepcopy(protpos_ref)
        line = line.rstrip()
        sample = line.split("\t")[0]
        print("sample: "+sample)
        nds = line.split("\t")[1]
        all_nodes = nds.split(" ")
        #site_waiting_muts = dict()
        for i in range(0,len(all_nodes)):
            string = all_nodes[i]
            node = string.split(":")[0]
            muts = string.split(":")[1]
            each_mut = muts.split(",")
             
            for mut in each_mut:
                prev_let = mut[0]
                new_let = mut[len(mut)-1]
                site = mut[1:(len(mut)-1)]
                site = int(site)
                 
                #print(str(site))
                current_let = protpos_nt[site]

                if current_let != prev_let:
                    print (string)
                    print (str(current_let)+"\t"+str(prev_let)+"\t"+str(new_let))
                    sys.exit()

                if new_let != current_let:
                    protpos_nt[site] = new_let
                
        
     
        fasta_seq = str()
        for site in sorted(protpos_nt):
            current_nt = protpos_nt[site]
             #current_aa = codon_aa[current_codon]
            fasta_seq = fasta_seq + current_nt
        
        ym = "reference"
        elements = sample.split("|")
        if len(elements) > 2:
            date = elements[2]
            subdates = date.split("-")
            if len(subdates) > 1:
                year = subdates[0]
                month = subdates[1]
                ym = str(year)+"-"+str(month)
            else:
                ym = "no_date"
                print(sample)
        else:
            ym = "no_date"
            print(sample)
        
        for n in range(0,len(prot_begins)):
            prot_begin = prot_begins[n]
            prot_end = prot_ends[n]
            prot_name = prot_names[n]

            refgene = refseq_lineage[(prot_begin-1):prot_end]
            refprot = ""
            for i in range(0,(len(refgene)-2),3):
                codon = refgene[i:(i+3)]
                if codon in codon_aa:
                    aa = codon_aa[codon]
                    refprot = refprot+aa
                else:
                    refprot = refprot+"-"


            
            gene = fasta_seq[(prot_begin-1):prot_end]
            prot = ""
            for i in range(0,(len(gene)-2),3):
                codon = gene[i:(i+3)]
                if codon in codon_aa:
                    aa = codon_aa[codon]
                    prot = prot+aa
                else:
                    prot = prot+"-"

            for k in range(0,len(prot)):
                site = k+1
                reflet = refprot[k]
                let = prot[k]
                if reflet != "-" and let != "-" and  ym != "reference":
                    line = prot_name+"_"+str(site)+"_"+reflet
                    line1 = prot_name+"_"+str(site)+"_"+reflet+"_"+let
                    prot_pos_month_times[line][ym] += 1
                    prot_pos_month_times[line]['total'] += 1
                    #if let != reflet:
                    prot_mut_month_times[line1][ym] += 1
                    prot_mut_month_times[line1]['total'] += 1
                    


        #RdRp
        begin1 = 13442
        end1  = 13468
        begin2 = 13468
        end2  = 16236
        prot_name = "RdRp"

        

        refprot = ""
        refgene1 = refseq_lineage[(begin1-1):end1]
        for i in range(0,(len(refgene1)-2),3):
            codon = refgene1[i:(i+3)]
            if codon in codon_aa:
                aa = codon_aa[codon]
                refprot = refprot+aa
            else:
                refprot = refprot+"-"

        refgene2 = refseq_lineage[(begin2-1):end2]
        for i in range(0,(len(refgene2)-2),3):
            codon = refgene2[i:(i+3)]
            if codon in codon_aa:
                aa = codon_aa[codon]
                refprot = refprot+aa
            else:
                refprot = refprot+"-"


        prot = ""
        gene1 = fasta_seq[(begin1-1):end1]
        for i in range(0,(len(gene1)-2),3):
            codon = gene1[i:(i+3)]
            if codon in codon_aa:
                aa = codon_aa[codon]
                prot = prot+aa
            else:
                prot = prot+"-"

        gene2 = fasta_seq[(begin2-1):end2]
        for i in range(0,(len(gene2)-2),3):
            codon = gene2[i:(i+3)]
            if codon in codon_aa:
                aa = codon_aa[codon]
                prot = prot+aa
            else:
                prot = prot+"-"

        for k in range(0,len(prot)):
            site = k+1
            reflet = refprot[k]
            let = prot[k]
            if reflet != "-" and let != "-" and  ym != "reference":
                line = prot_name+"_"+str(site)+"_"+reflet
                line1 = prot_name+"_"+str(site)+"_"+reflet+"_"+let
                prot_pos_month_times[line][ym] += 1
                prot_pos_month_times[line]['total'] += 1
                #if let != reflet:
                prot_mut_month_times[line1][ym] += 1
                prot_mut_month_times[line1]['total'] += 1



outf = open("GISAID_FromUShER_7thSept2023."+voc_lineage+".AllMuts.MONTHS.tsv","w")
outf.write("prot_name"+"\t"+"site"+"\t"+"wt_let"+"\t"+"mut_let"+"\t"+"month"+"\t"+"mut_occurrences"+"\t"+"total_sequences"+"\t"+"fraction"+"\n")
for line in prot_mut_month_times:
    for month in prot_mut_month_times[line]:
        occurrences = prot_mut_month_times[line][month]
        prot = line.split("_")[0]
        site = line.split("_")[1]
        reflet = line.split("_")[2]
        mut = line.split("_")[3]
        key = prot+"_"+str(site)+"_"+reflet
        covered = prot_pos_month_times[key][month]
        fraction = occurrences/covered
        outf.write(prot+"\t"+str(site)+"\t"+str(reflet)+"\t"+str(mut)+"\t"+str(month)+"\t"+str(occurrences)+"\t"+str(covered)+"\t"+str(fraction)+"\n")
    
outf.close()

In [ ]:
#script to collect EVs from GISAID 
import re
#from ete3 import Tree
import optparse
from collections import defaultdict
import itertools
import random
import copy
import sys
#from datetime import datetime

parser=optparse.OptionParser()
parser.add_option('-p', '--paths', help='', type='str')
#parser.add_option('-t', '--town', help='', type='str')
options, args=parser.parse_args()

paths = options.paths
voc_lineage = paths.replace(".paths.tsv","")
#town = options.town

prot_begin_end = defaultdict(lambda: defaultdict(list))
#with open("immun_epit_all.csv") as pept_file:
with open("immun_epit_all3.csv") as pept_file:
    colnames = pept_file.readline()
    for line in pept_file:
        inf = line.split(";")
        pr = inf[0]
        begin = inf[3]
        end = inf[4]
        begin = begin.replace(".0","")
        begin = int(begin)
        end = end.replace(".0","")
        end = int(end)
        prot_begin_end[pr][begin].append(end)
        seq = inf[1]
        

codon_aa = dict()
with open("genetic_code") as codon_table:
    for line in codon_table:
        codon = line.split(" ")[0]
        aa = line.split(" ")[1]
        codon_aa[codon] = aa

prot_begins = ["266","806","2720","8555","10055","10973","11843","12092","12686","13025","16237","18040","19621","20659","21563","25393","26245","26523","27202","27394","27756","27894","28274","29558"]
prot_begins = [eval(i) for i in prot_begins]

prot_ends = ["805","2719","8554","10054","10972","11842","12091","12685","13024","13441","18039","19620","20658","21552","25384","26220","26472","27191","27387","27759","27887","28259","29533","29674"]
prot_ends = [eval(i) for i in prot_ends]

prot_names = ["leader","nsp2","nsp3","nsp4","3C","nsp6","nsp7","nsp8","nsp9","nsp10","helicase","exonuclease","endornase","methyltransferase","Spike","ORF3a","E","M","ORF6","ORF7a","ORF7b","ORF8","N","ORF10"]


ref_file_lineage = open('OmicronReference.fasta', 'r')
firstLine = ref_file_lineage.readline()
refseq_lineage = ref_file_lineage.readline().rstrip()

protpos_ref = dict()
ref_file = open('/gss/home/e.riumina/Galya_Guest/ReferenceWuhan.one_line.fasta', 'r')
firstLine = ref_file.readline()
refseq = ref_file.readline().rstrip()
for k in range(1,len(refseq)+1):
    nt = refseq[(k-1)]
    k = int(k)
    protpos_ref[k] = nt


#######################################################
coord_seq = dict()
for k in range (1,len(prot_names)+1):
    protname = prot_names[k-1]
    prot_begin = prot_begins[k-1]
    prot_end = prot_ends[k-1]
    refgene = refseq_lineage[(prot_begin-1):prot_end]
    refprot = ""
    for i in range(0,(len(refgene)-2),3):
        codon = refgene[i:(i+3)]
        if codon in codon_aa:
            aa = codon_aa[codon]
            refprot = refprot+aa
        else:
            refprot = refprot+"-"

    begin_end = prot_begin_end[protname]
    for beg in begin_end:
        for end in begin_end[beg]:
            coord = protname+"_"+str(beg)+"_"+str(end)
            ref_peptide_seq = refprot[(beg-1):end]
            coord_seq[coord] = ref_peptide_seq
            print(coord+"\t"+ref_peptide_seq)



begin1 = 13442
end1  = 13468
begin2 = 13468
end2  = 16236
protname = "RdRp"

refprot = ""
refgene1 = refseq_lineage[(begin1-1):end1]
for i in range(0,(len(refgene1)-2),3):
    codon = refgene1[i:(i+3)]
    if codon in codon_aa:
        aa = codon_aa[codon]
        refprot = refprot+aa
    else:
        refprot = refprot+"-"
        
refgene2 = refseq_lineage[(begin2-1):end2]
for i in range(0,(len(refgene2)-2),3):
    codon = refgene2[i:(i+3)]
    if codon in codon_aa:
        aa = codon_aa[codon]
        refprot = refprot+aa
    else:
        refprot = refprot+"-"

begin_end = prot_begin_end[protname]
for beg in begin_end:
    for end in begin_end[beg]:
        coord = protname+"_"+str(beg)+"_"+str(end)
        ref_peptide_seq = refprot[(beg-1):end]
        coord_seq[coord] = ref_peptide_seq
        print(coord+"\t"+ref_peptide_seq)
#sys.exit()
########################################################


countries = ["Argentina","Armenia","Austria","Brazil","Chile","China","Colombia","Croatia","CzechRepublic","France","Germany","Greece","Iran","Iraq","Ireland","NorthernIreland","Italy","Japan","Jordan","South Korea","Malaysia","Mexico","Netherlands","Nigeria","Norway","Poland","Portugal","Romania","Russia","Slovakia","Spain","SriLanka","Sweden","Switzerland","Thailand","Turkey","UnitedArabEmirates","Israel"]

prot_mut_month_times = defaultdict(lambda: defaultdict(int))
prot_pos_month_times = defaultdict(lambda: defaultdict(int))
with open(options.paths) as mut_file:
    for line in mut_file:
        protpos_nt = copy.deepcopy(protpos_ref)
        line = line.rstrip()
        sample = line.split("\t")[0]

        country = sample.split("/")[0]
        country = country.replace(" ","")
        country = country.replace("_","")

        print("sample: "+sample)
        nds = line.split("\t")[1]
        all_nodes = nds.split(" ")
        #site_waiting_muts = dict()
        for i in range(0,len(all_nodes)):
            string = all_nodes[i]
            node = string.split(":")[0]
            muts = string.split(":")[1]
            each_mut = muts.split(",")

            for mut in each_mut:
                prev_let = mut[0]
                new_let = mut[len(mut)-1]
                site = mut[1:(len(mut)-1)]
                site = int(site)

                #print(str(site))
                current_let = protpos_nt[site]

                if current_let != prev_let:
                    print (string)
                    print (str(current_let)+"\t"+str(prev_let)+"\t"+str(new_let))
                    sys.exit()

                if new_let != current_let:
                    protpos_nt[site] = new_let
                    #print (sample)
                    #print(mut)
                    #sys.exit()
                    


        fasta_seq = str()
        for site in sorted(protpos_nt):
            current_nt = protpos_nt[site]
             #current_aa = codon_aa[current_codon]
            fasta_seq = fasta_seq + current_nt

        ym = "reference"
        elements = sample.split("|")
        if len(elements) > 2:
            date = elements[2]
            subdates = date.split("-")
            if len(subdates) > 1:
                year = subdates[0]
                month = subdates[1]
                ym = str(year)+"-"+str(month)
            else:
                ym = "no_date"
                print(sample)
        else:
            ym = "no_date"
            print(sample)

        
        for n in range(0,len(prot_begins)):
            prot_begin = prot_begins[n]
            prot_end = prot_ends[n]
            prot_name = prot_names[n]
            #print(prot_name)
            #print(str(prot_begin))
            #print(str(prot_end))

            refgene = refseq_lineage[(prot_begin-1):prot_end]
            refprot = ""
            for i in range(0,(len(refgene)-2),3):
                codon = refgene[i:(i+3)]
                if codon in codon_aa:
                    aa = codon_aa[codon]
                    refprot = refprot+aa
                else:
                    refprot = refprot+"-"
            #print (refprot)

            gene = fasta_seq[(prot_begin-1):prot_end]
            prot = ""
            for i in range(0,(len(gene)-2),3):
                codon = gene[i:(i+3)]
                if codon in codon_aa:
                    aa = codon_aa[codon]
                    prot = prot+aa
                else:
                    prot = prot+"-"
            #print(prot)

            begin_end = prot_begin_end[prot_name]
            for beg in begin_end:
                for end in begin_end[beg]:
                    line = prot_name+"_"+str(beg)+"_"+str(end)+"_"
                    line_1 = prot_name+"_"+str(beg)+"_"+str(end)
                    
                    gaps = 0
                    muts = 0
                    for k in range((beg-1),end):
                        reflet = refprot[k]
                        let = prot[k]
                        if reflet != "-" and let != "-" and let != reflet:
                            mut = reflet+str(k+1)+let
                            line = line+mut+","
                            muts += 1
                        elif reflet != "-" and let == "-":
                            gaps += 1
                    #print(str(gaps))
                    #print(str(muts))

                    line_gisaid = "gisaid_"+line
                    line_1_gisaid = "gisaid_"+line_1
                    if gaps == 0 and ym != "reference":
                        #print (line_1_gisaid)
                        #print(line_gisaid)
                        prot_pos_month_times[line_1_gisaid][ym] += 1
                        prot_pos_month_times[line_1_gisaid]['total'] += 1
                        if country in countries:
                            line_1_country = country+"_"+line_1
                            prot_pos_month_times[line_1_country][ym] += 1
                            prot_pos_month_times[line_1_country]['total'] += 1
                        if country == "NorthernIreland" or country == "Scotland" or country == "England" or country == "Wales":
                            line_1_country = "UnitedKingdom_"+line_1
                            prot_pos_month_times[line_1_country][ym] += 1
                            prot_pos_month_times[line_1_country]['total'] += 1

                        if muts > 0:
                            line_gisaid = line_gisaid[:-1]
                            line = line[:-1]
                            #print(line_gisaid)
                            #print(line)
                            #sys.exit()
                            prot_mut_month_times[line_gisaid][ym] += 1
                            prot_mut_month_times[line_gisaid]['total'] += 1
                            if country in countries:
                                line_country = country+"_"+line
                                prot_mut_month_times[line_country][ym] += 1
                                prot_mut_month_times[line_country]['total'] += 1
                            if country == "NorthernIreland" or country == "Scotland" or country == "England" or country == "Wales":
                                line_country = "UnitedKingdom_"+line
                                prot_mut_month_times[line_country][ym] += 1
                                prot_mut_month_times[line_country]['total'] += 1
                        else:
                            line_gisaid = line_gisaid+"wt"
                            line = line+"wt"
                            prot_mut_month_times[line_gisaid][ym] += 1
                            prot_mut_month_times[line_gisaid]['total'] += 1
                            if country in countries:
                                line_country = country+"_"+line
                                prot_mut_month_times[line_country][ym] += 1
                                prot_mut_month_times[line_country]['total'] += 1
                            if country == "NorthernIreland" or country == "Scotland" or country == "England" or country == "Wales":
                                line_country = "UnitedKingdom_"+line
                                prot_mut_month_times[line_country][ym] += 1
                                prot_mut_month_times[line_country]['total'] += 1
            
                  
        #RdRp
        begin1 = 13442
        end1  = 13468
        begin2 = 13468
        end2  = 16236
        prot_name = "RdRp"

        refprot = ""
        refgene1 = refseq_lineage[(begin1-1):end1]
        for i in range(0,(len(refgene1)-2),3):
            codon = refgene1[i:(i+3)]
            if codon in codon_aa:
                aa = codon_aa[codon]
                refprot = refprot+aa
            else:
                refprot = refprot+"-"
                
        refgene2 = refseq_lineage[(begin2-1):end2]
        for i in range(0,(len(refgene2)-2),3):
            codon = refgene2[i:(i+3)]
            if codon in codon_aa:
                aa = codon_aa[codon]
                refprot = refprot+aa
            else:
                refprot = refprot+"-"

        prot = ""
        gene1 = fasta_seq[(begin1-1):end1]
        for i in range(0,(len(gene1)-2),3):
            codon = gene1[i:(i+3)]
            if codon in codon_aa:
                aa = codon_aa[codon]
                prot = prot+aa
            else:
                prot = prot+"-"

        gene2 = fasta_seq[(begin2-1):end2]
        for i in range(0,(len(gene2)-2),3):
            codon = gene2[i:(i+3)]
            if codon in codon_aa:
                aa = codon_aa[codon]
                prot = prot+aa
            else:
                prot = prot+"-"

        begin_end = prot_begin_end[prot_name]
        for beg in begin_end:
            for end in begin_end[beg]:
                line = prot_name+"_"+str(beg)+"_"+str(end)+"_"
                line_1 = prot_name+"_"+str(beg)+"_"+str(end)
                gaps = 0
                muts = 0
                for k in range((beg-1),end):
                    reflet = refprot[k]
                    let = prot[k]
                    if reflet != "-" and let != "-" and let != reflet:
                        mut = reflet+str(k+1)+let
                        line = line+mut+","
                        muts += 1
                    elif reflet != "-" and let == "-":
                        gaps += 1
                        
                line_gisaid = "gisaid_"+line
                line_1_gisaid = "gisaid_"+line_1
                if gaps == 0 and ym != "reference":
                    prot_pos_month_times[line_1_gisaid][ym] += 1
                    prot_pos_month_times[line_1_gisaid]['total'] += 1
                    if country in countries:
                        line_1_country = country+"_"+line_1
                        prot_pos_month_times[line_1_country][ym] += 1
                        prot_pos_month_times[line_1_country]['total'] += 1
                    if country == "NorthernIreland" or country == "Scotland" or country == "England" or country == "Wales":
                        line_1_country = "UnitedKingdom_"+line_1
                        prot_pos_month_times[line_1_country][ym] += 1
                        prot_pos_month_times[line_1_country]['total'] += 1

                    if muts > 0:
                        line_gisaid = line_gisaid[:-1]
                        line = line[:-1]
                        prot_mut_month_times[line_gisaid][ym] += 1
                        prot_mut_month_times[line_gisaid]['total'] += 1
                        if country in countries:
                            line_country = country+"_"+line
                            prot_mut_month_times[line_country][ym] += 1
                            prot_mut_month_times[line_country]['total'] += 1
                        if country == "NorthernIreland" or country == "Scotland" or country == "England" or country == "Wales":
                            line_country = "UnitedKingdom_"+line
                            prot_mut_month_times[line_country][ym] += 1
                            prot_mut_month_times[line_country]['total'] += 1
                    else:
                        line_gisaid = line_gisaid+"wt"
                        line = line+"wt"
                        prot_mut_month_times[line_gisaid][ym] += 1
                        prot_mut_month_times[line_gisaid]['total'] += 1
                        if country in countries:
                            line_country = country+"_"+line
                            prot_mut_month_times[line_country][ym] += 1
                            prot_mut_month_times[line_country]['total'] += 1
                        if country == "NorthernIreland" or country == "Scotland" or country == "England" or country == "Wales":
                            line_country = "UnitedKingdom_"+line
                            prot_mut_month_times[line_country][ym] += 1
                            prot_mut_month_times[line_country]['total'] += 1

print(str(len(prot_mut_month_times)))
#sys.exit()

outf = open("GISAIDandCountries_FromUShER_7thSept2023."+voc_lineage+".EpitopeVariants.MONTHS.tsv","w")
outf.write("country"+"\t"+"prot_name"+"\t"+"begin"+"\t"+"end"+"\t"+"wt_seq"+"\t"+"mutations"+"\t"+"month"+"\t"+"mut_occurrences"+"\t"+"total_sequences"+"\t"+"fraction"+"\n")
for line in prot_mut_month_times:
#    print(line)
    for month in prot_mut_month_times[line]:
#        print(str(month))
        occurrences = prot_mut_month_times[line][month]
#        print(str(occurrences))
        country = line.split("_")[0]
#        print(country)
        prot = line.split("_")[1]
#        print(prot)
        first_pos = line.split("_")[2]
        last_pos = line.split("_")[3]
        key = country+"_"+prot+"_"+first_pos+"_"+last_pos
#        print(key)
        muts = line.split("_")[4]
#        print(muts)
        covered = prot_pos_month_times[key][month]
#        print(str(covered))
        fraction = occurrences/covered
        key1 = prot+"_"+first_pos+"_"+last_pos
        ref_peptide_seq = coord_seq[key1]

        outf.write(country+"\t"+prot+"\t"+str(first_pos)+"\t"+str(last_pos)+"\t"+ref_peptide_seq+"\t"+muts+"\t"+str(month)+"\t"+str(occurrences)+"\t"+str(covered)+"\t"+str(fraction)+"\n")
        
outf.close()

In [4]:
#for VOC root mutations
immun_merge = pd.read_csv('immun_epit_all3.csv', sep = '\t').replace('Spike', 'spike')
mut_table = pd.read_csv('Fig1/mutations.csv', index_col = 0, sep = '\t').replace('Spike', 'spike')
prots = pd.read_csv('Fig1/wuhan_sequences.csv').replace('Spike', 'spike')
prots_dict = dict(zip(prots['name1'].values,prots['name3'].values))

mut_table = mut_table[(~mut_table['name'].str.contains('del'))&(~mut_table['name'].str.contains('ins'))&(~mut_table['name'].str.contains('\*'))]
mut_table['gene'] = [prots_dict[i] for i in mut_table['gene']]
mut_table['pos'] = [i.split(':')[1][1:-1] for i in mut_table['name']]
mut_table['pr_pos'] = mut_table['gene'] + '_' + mut_table['pos']

poses = []
imm = []
imm_tables = []

for pos in set(mut_table['pr_pos'].replace('Spike', 'spike')):
    #print(pos)
    table = immun_merge[(immun_merge['prot_name'] == pos.split('_')[0]) & 
                    (immun_merge['Coordinates start'] <= int(pos.split('_')[1])) &
                    (immun_merge['Coordinates end'] >=  int(pos.split('_')[1]))].copy()
    table['pr_pos'] = pos
    imm_tables.append(table)
imm_strains = pd.concat(imm_tables)

all_all_strains = pd.merge(mut_table, imm_strains, on = ['pr_pos']).rename(columns = {'Coordinates start':'begin', 'Coordinates end':'end', 'Allele Name_x':'Allele Name'})
all_all_strains['mutations'] = [i.split(':')[1] for i in all_all_strains['name']]
def get_mut_peptides(all_country):
    all_country = all_country[~all_country['mutations'].str.contains('\*')]
    all_country['peptide_mut'] = 0
    for index, row in all_country.iterrows():
        pept = row['peptide']
        #print(index)
        check = 0
        mut = row['mutations']
        coord_mut = int(mut[1:-1])
            #print(coord_mut, row['Immun_start'], row['Immun_end'])
        if (coord_mut >= row['begin']) & (coord_mut <= row['end']):
            aa_mut = mut[-1] 
            pept_mut = pept[:coord_mut - int(row['begin'])] + aa_mut.upper() + pept[coord_mut - int(row['begin'])+1:]        
            pept = pept_mut
            check = 1
        else:
            print('ERROOOOOOOOOOOOOOOOOOOOOOOOOOOOOR')
        if check == 0:
                pept_mut = '_'
        #print(pept_mut)
        all_country.loc[index, 'peptide_mut'] = pept_mut
    print(all_country.shape, 'pre_final')
    all_country['prot_name'] = all_country['prot_name'].replace({'spike':'Spike'})
    return all_country
all_mut_pept = get_mut_peptides(all_all_strains)
all_mut_pept.to_csv('Strains_beforeMHCpan_WithoutFreqs.csv', index = False)

,name,strain,reccurent,mut_type,gene,coord,imm,pos,pr_pos,prot_name,peptide,Length,begin,end,Allele Name,mutations
0,ns8:R52I,alpha,no,subst,ORF8,9309,True,52,ORF8_52,ORF8,GARKSAPLI,9,50,58,HLA-A02:01,R52I
1,ns8:Y73C,alpha,no,subst,ORF8,9330,True,73,ORF8_73,ORF8,YIDIGNYTV,9,73,81,HLA-A02:01,Y73C
2,nsp3:A890D,alpha,no,subst,nsp3,1708,True,890,nsp3_890,nsp3,ARAGEAANF,9,884,892,HLA-C07:01,A890D
3,nsp3:A890D,alpha,no,subst,nsp3,1708,True,890,nsp3_890,nsp3,GEAANFCAL,9,887,895,HLA-B40:01,A890D
4,nsp3:A890D,alpha,no,subst,nsp3,1708,True,890,nsp3_890,nsp3,AANFCALILA,10,889,898,HLA-A02:01,A890D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,S:S375F,omicron,no,subst,spike,7484,True,375,spike_375,spike,SASFSTFKCY,10,371,380,HLA-A01:01,S375F
245,S:Y505H,omicron,no,subst,spike,7614,True,505,spike_505,spike,FQPTNGVGY,9,497,505,HLA-B15:01,Y505H
246,S:Y505H,omicron,no,subst,spike,7614,True,505,spike_505,spike,NGVGYQPYR,9,501,509,HLA-A33:03,Y505H
247,S:Y505H,omicron,no,subst,spike,7614,True,505,spike_505,spike,VGYQPYRVV,9,503,511,HLA-C06:02,Y505H
248,S:Y505H,omicron,no,subst,spike,7614,True,505,spike_505,spike,YQPYRVVVL,9,505,513,HLA-C06:02,Y505H

In [ ]:
#the following analysis includes only gisaid data for EVs. It was also performed for individuals mutations, 
#in this case files "GISAIDandCountries_FromUShER_7thSept2023.Omicron.EpitopeVariants.MONTHS.tsv"
#and "GISAIDandCountries_FromUShER_7thSept2023.Delta.EpitopeVariants.MONTHS.tsv" should be replaces with:
#'Data/GISAID_FromUShER_7thSept2023.Omicron.AllMuts.MONTHS.tsv' and 'Data/GISAID_FromUShER_7thSept2023.Omicron.AllMuts.MONTHS.tsv'


#function to obtain mutated peptides
def get_mut_peptides(table):
    search = table['mutations'].str.extractall('([A-Z]\d+[A-Z])')
    search = search.unstack()
    search.columns = search.columns.droplevel() +1
    search = search.assign(mut_list = search.stack().groupby(level=0).agg(list))
    search = search['mut_list']
    all_country = pd.concat([table, search], axis=1).fillna('wt')
    print(all_country.shape, 'shouldnt change')
    
    all_country = all_country[~all_country['mutations'].str.contains('\*')]
    #get mutated peptides
    all_country['peptide_mut'] = 0
    for index, row in all_country.iterrows():
        pept = row['peptide']
        #print(index)
        check = 0
        if row['mut_list'] == 'wt':
            pept_mut = row['peptide']
        else:
            for mut in row['mut_list'] :
                #print(mut,row['mut_list'])
                coord_mut = int(mut[1:-1])
            #print(coord_mut, row['Immun_start'], row['Immun_end'])
                if (coord_mut >= row['begin']) & (coord_mut <= row['end']):
                    aa_mut = mut[-1]
                
                    pept_mut = pept[:coord_mut - int(row['begin'])] + aa_mut.upper() + pept[coord_mut - int(row['begin'])+1:]        
                    pept = pept_mut
                    check = 1
                else:
                    print('ERROOOOOOOOOOOOOOOOOOOOOOOOOOOOOR')
            if check == 0:
                pept_mut = '_'
        #print(pept_mut)
        all_country.loc[index, 'peptide_mut'] = pept_mut
    print(all_country.shape, 'pre_final')
    all_country['prot_name'] = all_country['prot_name'].replace({'spike':'Spike'})
    return all_country

In [ ]:
names = ['gisaid','UnitedKingdom','Switzerland', 'Netherlands', 'Croatia', 'Poland', 'Romania', 'Norway', 'Sweden', 'Spain', 'Russia','Italy', 'Slovakia', 'Germany',  'Ireland','Austria', 'Portugal','CzechRepublic',  'France', 'Greece','Turkey',  'UnitedArabEmirates', 'SouthKorea', 'Japan', 'Malaysia','Thailand','SriLanka', 'Nigeria', 'Brazil','Colombia', 'Argentina','Chile','Mexico']
#for files with EVs:
data_om = pd.read_csv('Data/GISAIDandCountries_FromUShER_7thSept2023.Omicron.EpitopeVariants.MONTHS.tsv', sep = '\t')
data_d = pd.read_csv('Data/GISAIDandCountries_FromUShER_7thSept2023.Delta.EpitopeVariants.MONTHS.tsv', sep = '\t')

data_om = data_om.rename(columns={'wt_seq':'peptide'})
data_d = data_d.rename(columns={'wt_seq':'peptide'})

d_all_tables = {}
om_all_tables = {}
for name in names:
    om_all_tables[name] = data_om[data_om['country'] == name]
    d_all_tables[name] = data_d[data_d['country'] == name]

om_mut_pept = {}
d_mut_pept = {}
for name in names:
    print(name)
    om_mut_pept[name] = get_mut_peptides(om_all_tables[name])
    d_mut_pept[name] = get_mut_peptides(d_all_tables[name])
    
#need to merge with immunogenic data to know corresponding HLA
immun1 = pd.read_csv('tcell_table_export_1701167238.csv', header=[0,1])
immun2 = pd.read_csv('tcell_table_export_1701167293.csv', header=[0,1])
immun3 = pd.read_csv('tcell_table_export_1701167144.csv', header=[0,1])
immun_I = pd.concat([immun1, immun2, immun3])
immun_I.columns = [c[0] + "_" + c[1] for c in immun_I.columns]
immun_I = immun_I[['Epitope_Name', 'MHC Restriction_Name', 'Epitope_Molecule Parent']].drop_duplicates().rename(columns = {'Epitope_Name':
                                                'peptide', 'MHC Restriction_Name':'Allele Name', 'Epitope_Molecule Parent':'ep_prot_name'})[['peptide','Allele Name', 'ep_prot_name']].fillna(0)

immun_I = immun_I[(immun_I['peptide'].str.len() <13) & (immun_I['peptide'].str.len() >7)&(immun_I['Allele Name'].str.contains(':'))]
immun_I = immun_I[(~immun_I['Allele Name'].str.startswith('HLA-D'))].drop_duplicates()
immun_I['Allele Name'] = immun_I['Allele Name'].str.replace('*', '')

om_mut_pept_hla = {}
d_mut_pept_hla = {}
for name in names:
    om_mut_pept_hla[name] = om_mut_pept[name].merge(immun_I, on = 'peptide')
    om_mut_pept_hla[name].to_csv('Omicron_' + name + '_beforeMHCpan_WithoutFreqs.csv', index = False)
    d_mut_pept_hla[name] = d_mut_pept[name].merge(immun_I, on = 'peptide')
    d_mut_pept_hla[name].to_csv('Delta_' + name + '_beforeMHCpan_WithoutFreqs.csv', index = False)

In [ ]:
names = ['gisaid','UnitedKingdom','Switzerland', 'Netherlands', 'Croatia', 'Poland', 'Romania', 'Norway', 'Sweden', 'Spain', 'Russia','Italy', 'Slovakia', 'Germany',  'Ireland','Austria', 'Portugal','CzechRepublic',  'France', 'Greece','Turkey',  'UnitedArabEmirates', 'SouthKorea', 'Japan', 'Malaysia','Thailand','SriLanka', 'Nigeria', 'Brazil','Colombia', 'Argentina','Chile','Mexico']

pept_for_netMHC = []
wt_pept_for_netMHC = []
HLA_for_netMHC = []

for name in names:
    pept_for_netMHC += set(om_mut_pept_hla[name]['peptide_mut'])
    wt_pept_for_netMHC += set(om_mut_pept_hla[name]['peptide'])
    HLA_for_netMHC += set(om_mut_pept_hla[name]['Allele Name'])
    
    pept_for_netMHC += set(d_mut_pept_hla[name]['peptide_mut'])
    wt_pept_for_netMHC += set(d_mut_pept_hla[name]['peptide'])
    HLA_for_netMHC += set(d_mut_pept_hla[name]['Allele Name'])

pept_for_netMHC_final = set(pept_for_netMHC)
wt_pept_for_netMHC_final = set(wt_pept_for_netMHC)
HLA_for_netMHC_final = set(HLA_for_netMHC)

with open('netMHCpan/mut_peptides_countries.txt', 'w') as f2:
    for i in set(pept_for_netMHC):
        f2.write("%s\n" % i)
with open('netMHCpan/wt_peptides_countries.txt', 'w') as f2:
    for i in wt_pept_for_netMHC:
        f2.write("%s\n" % i)
#those are the HLA alleles that you need to run netMHCpan with
for i in set(HLA_for_netMHC_final):
    print(i)

In [ ]:


#!/bin/bash
#PBS -d .
#PBS -l walltime=10:00:00
/gss/home/e.riumina/netMHCpan-4.1/netMHCpan -p /gss/home/e.riumina/Dec_31_final/mut_peptides_countries6.txt -BA -xls -a HLA-B51:01,HLA-A30:01,HLA-A02:06,HLA-A33:03,HLA-A03:01,HLA-A29:02,HLA-B52:01,HLA-A33:01,HLA-A02:01,HLA-A30:02,HLA-A32:01,HLA-B35:02,HLA-A68:01,HLA-B13:02,HLA-A68:02,HLA-C12:03,HLA-B08:01,HLA-B57:01,HLA-B44:10,HLA-C07:02,HLA-A02:07,HLA-A31:01,HLA-B53:01,HLA-B15:01,HLA-C14:02,HLA-B13:01,HLA-B40:01,HLA-A23:01,HLA-C15:02,HLA-B44:02,HLA-B57:03,HLA-A24:02,HLA-B44:03,HLA-C07:01,HLA-C16:02,HLA-B35:01,HLA-B40:10,HLA-A11:02,HLA-A26:01,HLA-A29:11,HLA-A11:01,HLA-A01:01,HLA-B07:02,HLA-A29:01,HLA-A02:03,HLA-B48:01,HLA-B39:01,HLA-C03:04,HLA-C04:01,HLA-A02:05,HLA-C06:02,HLA-B27:05,HLA-B49:01 -xlsfile /gss/home/e.riumina/Dec_31_final/mut_countries_out.xls > /gss/home/e.riumina/Dec_31_final/mut_countries_out.txt
#an examaple of netMHCpan run

In [5]:
def fix_header_MHCpan(file_name):
    snp_MHC_names =pd.read_csv(file_name, sep='\t', header = [1], nrows=3)
    snp_MHC_hlas =pd.read_csv(file_name, sep='\t', header = 0, nrows=2).columns
    hlas = ['']
    hlas+=[i for i in snp_MHC_hlas if i.startswith('HLA') for j in range(2)]
    to_del = [i for i in snp_MHC_names.columns if ('Pos'in i) | ('ID' in i) | ('NB' in i)| ('core' in i)| ('icore' in i)|('Ave' in i)]
    names_col = [i for i in snp_MHC_names.columns if i not in to_del]
    my_list = []
    for chunk in pd.read_csv(file_name, sep='\t', header = 1, usecols = names_col, chunksize=50000):
        chunk[chunk.select_dtypes(np.float64).columns] = chunk.select_dtypes(np.float64).astype(np.float32)
        my_list.append(chunk)
    snp_MHC = pd.concat(my_list, axis= 0)
    del my_list
    new = [m+' ' + str(n) for m,n in zip(hlas,snp_MHC.columns)]
    new_2 = [re.sub('\.\d*', '', i) for i in new]
    snp_MHC.columns = new_2
    del snp_MHC_names, snp_MHC_hlas, new 
    return snp_MHC

In [ ]:
#use here your netMHCpan output
wt_netMHC = fix_header_MHCpan('netMHCpan/wt_countries_out.xls')#
mut_netMHC = fix_header_MHCpan('netMHCpan/mut_countries_out.xls')#
netMHC = pd.concat([wt_netMHC,mut_netMHC])

In [7]:
merged_new = []
def fromNetMHCpan(table):
    tables = []
    for hla in set(table['Allele Name'].values):        
        table_before_hla = table[table['Allele Name'] == hla]
        columns_netMHC = [' Peptide']
        columns_netMHC += netMHC.columns[netMHC.columns.str.startswith(hla)].to_list()
        table_netMHC = netMHC[columns_netMHC].drop_duplicates()
        table_before_hla_wt = table_before_hla.merge(table_netMHC, left_on = 'peptide', right_on = ' Peptide', how = 'left')
        table_before_hla_wt.rename(columns={hla + ' EL_Rank':'wt_EL_Rank', hla + ' BA_Rank':'wt_BA_Rank'}, inplace=True)

        table_before_hla_wt_mut = table_before_hla_wt.merge(table_netMHC, left_on = 'peptide_mut', right_on = ' Peptide', how = 'left')
        table_before_hla_wt_mut.rename(columns={hla + ' EL_Rank':'mut_EL_Rank', hla + ' BA_Rank':'mut_BA_Rank'}, inplace=True)
        tables.append(table_before_hla_wt_mut)
        #print(table_before)
    all_country_after = pd.concat(tables)
    print(all_country_after.shape, table.shape)
    all_country_after = all_country_after.drop([' Peptide_x', ' Peptide_y'], axis=1)
    return all_country_after    
#make binding categories
def make_mark_EL(row):
    if (row['mut_EL_Rank'] <=2) & (row['wt_EL_Rank'] <=2) & (row['mut_EL_Rank'] >= 1.5*row['wt_EL_Rank']):
        return 'Decreased binding'
    elif (row['wt_EL_Rank'] <=2) & (row['mut_EL_Rank'] < row['wt_EL_Rank'])& (1.5*row['mut_EL_Rank'] <= row['wt_EL_Rank']):
        return 'Increased binding'
    elif (row['mut_EL_Rank'] >2) & (row['wt_EL_Rank'] <=2):
        return 'Lost binding'
    elif row['wt_EL_Rank'] >2:
        return 'No binding'
    else:
        return 'Same'
def make_mark_EL_wt(row):
    if (row['wt_EL_Rank'] >2):
        return 'No binding'
    elif (row['wt_EL_Rank'] <=2) & (row['wt_EL_Rank'] >0.5):
        return 'weak binder'
    elif (row['wt_EL_Rank'] <=0.5):
        return 'strong binder'

In [ ]:
names = ['gisaid','UnitedKingdom','Switzerland', 'Netherlands', 'Croatia', 'Poland', 'Romania', 'Norway', 'Sweden', 'Spain', 'Russia','Italy', 'Slovakia', 'Germany',  'Ireland','Austria', 'Portugal','CzechRepublic',  'France', 'Greece','Turkey',  'UnitedArabEmirates', 'SouthKorea', 'Japan', 'Malaysia','Thailand','SriLanka', 'Nigeria', 'Brazil','Colombia', 'Argentina','Chile','Mexico']#set(data_om['country'])
om_netMHCpan = {}
d_netMHCpan = {}
for name in names:
    d_table = pd.read_csv('Delta_' + name + '_beforeMHCpan_WithoutFreqs.csv', index_col = False)
    om_table = pd.read_csv('Omicron_' + name + '_beforeMHCpan_WithoutFreqs.csv', index_col = False)
    om_netMHCpan[name] = fromNetMHCpan(om_table)
    d_netMHCpan[name] = fromNetMHCpan(d_table)
    om_netMHCpan[name]['EL_Rank'] = [row[0] if row[1] == 'wt' else row[2] for row in om_netMHCpan[name][['wt_EL_Rank', 'mutations', 'mut_EL_Rank']].to_numpy()]
    d_netMHCpan[name]['EL_Rank'] = [row[0] if row[1] == 'wt' else row[2] for row in d_netMHCpan[name][['wt_EL_Rank', 'mutations', 'mut_EL_Rank']].to_numpy()]
    om_netMHCpan[name]['EL_mark'] = om_netMHCpan[name].apply(lambda row: make_mark_EL(row), axis=1).astype("str")
    om_netMHCpan[name]['EL_mark_wt'] = om_netMHCpan[name].apply(lambda row: make_mark_EL_wt(row), axis=1).astype("str")
    d_netMHCpan[name]['EL_mark'] = d_netMHCpan[name].apply(lambda row: make_mark_EL(row), axis=1).astype("str")
    d_netMHCpan[name]['EL_mark_wt'] = d_netMHCpan[name].apply(lambda row: make_mark_EL_wt(row), axis=1).astype("str")
    om_netMHCpan[name].to_csv('Omicron_' + name + '_Ranks_WithoutFreqs.csv', index = False)
    d_netMHCpan[name].to_csv('Delta_' + name + '_Ranks_WithoutFreqs.csv', index = False)

strains_netMHCpan = fromNetMHCpan(pd.read_csv('Strains_beforeMHCpan_WithoutFreqs.csv', index_col = False))
strains_netMHCpan['EL_Rank'] = [row[0] if row[1] == 'wt' else row[2] for row in strains_netMHCpan[['wt_EL_Rank', 'mutations', 'mut_EL_Rank']].to_numpy()]
strains_netMHCpan['EL_mark'] = strains_netMHCpan.apply(lambda row: make_mark_EL(row), axis=1).astype("str")
strains_netMHCpan['EL_mark_wt'] = strains_netMHCpan.apply(lambda row: make_mark_EL_wt(row), axis=1).astype("str")
strains_netMHCpan#.to_csv('Strains_Ranks_WithoutFreqs.csv', index = False)

In [ ]:
#round HLA up to first field
hla = pd.read_csv('HLAs.csv', sep = ',', usecols = ['Allele', 'Allele frequency', 'Population', 'type'])
hla['country'] = [('').join(i.split(' ')[:3]) for i in hla['Population']]
countries = ['UnitedKingdom','Switzerland', 'Netherlands', 'Croatia', 'Poland', 'Romania', 'Norway', 'Sweden', 'Spain', 'Russia','Italy', 'Slovakia', 'Germany',  'Ireland','Austria', 'Portugal','CzechRepublic',  'France', 'Greece','Turkey',  'UnitedArabEmirates','SouthKorea',  'Japan', 'Malaysia','Thailand','SriLanka', 'Nigeria', 'Brazil','Colombia', 'Argentina','Chile','Mexico']

ds_types = ['city', 'state', 'country']
for ds_type in ds_types:
    for name in countries:
        print(name)
        hla_freq = hla[(hla['country'].str.contains(name))&(hla['type'] == ds_type)]
        if (hla_freq.shape[0] >0):
            ds_type = hla_freq['type'].values[0]
            hla_freq['Allele Name'] = ['HLA-'+i[0] + i[2:4] for i in hla_freq['Allele'].values]
            HLA = hla_freq.groupby(['Allele Name']).sum().reset_index(level='Allele Name')

            om_nofreq = pd.read_csv('Omicron_' + name + '_Ranks_WithoutFreqs.csv', index_col = False)
            om_nofreq['HLA'] =  om_nofreq['Allele Name']
            om_nofreq['Allele Name'] = [i.split(':')[0] for i in om_nofreq['Allele Name'].values]
            tab_short = pd.merge(HLA, om_nofreq, on = 'Allele Name', how = 'right').fillna('no_freq')
            grouped = tab_short[tab_short['mutations']!='wt'].drop_duplicates(['prot_name','peptide','begin', 'mutations', 'HLA']).groupby(
                ['prot_name','peptide','begin', 'mutations', 'Allele Name']).agg({'HLA':('_').join, 'month':'size', 'EL_mark':('_').join,'mut_occurrences':'first'}).reset_index()
            broken = grouped[(grouped['EL_mark'].str.contains('Lost binding'))]
            more1 = grouped[(grouped['EL_mark'].str.contains('Lost binding'))&(grouped['month']>1)]
            more1['EL_mark'] = 'Lost binding'
            more1['check'] = '>2'
            increased = grouped[(grouped['EL_mark'].str.contains('Increased binding'))]
            more1_incr = grouped[(grouped['EL_mark'].str.contains('Increased binding'))&(grouped['month']>1)]
            more1_incr['EL_mark'] = 'Increased binding'
            more1_incr['check'] = '>2'
            tab = pd.merge(tab_short, pd.concat([more1, more1_incr])[['prot_name','peptide', 'mutations', 'Allele Name', 'EL_mark',
                                        'check']], on = ['prot_name','peptide', 'mutations', 'Allele Name'], how = 'left')
            tab['EL_mark'] = [row[2] if row[1] == '>2' else row[0] for row in zip(tab['EL_mark_x'], tab['check'],tab['EL_mark_y'])]
            tab = tab.groupby(['prot_name','peptide','begin', 'mutations', 'Allele Name', 'EL_mark', 'month', 'peptide_mut']).agg({'Allele frequency':'first',
                    'mut_occurrences':'first', 'HLA':('_').join, 'fraction':'first', 'wt_EL_Rank':'first', 'mut_EL_Rank':'first', 'total_sequences':'first', 'mut_occurrences':'first'}).reset_index()
            tab['Allele frequency'] = tab['Allele frequency'].astype('str')
            tab.to_csv(ds_type+'/Omicron_' + ds_type + '_'+ name + '_Ranks_RoundedHLA.csv', index = False)


            d_nofreq = pd.read_csv('Delta_' + name + '_Ranks_WithoutFreqs.csv', index_col = False)
            d_nofreq['HLA'] = d_nofreq['Allele Name']
            d_nofreq['Allele Name'] = [i.split(':')[0] for i in d_nofreq['Allele Name'].values]
            tab_short = pd.merge(HLA, d_nofreq, on = 'Allele Name', how = 'right').fillna('no_freq')
            grouped = tab_short[tab_short['mutations']!='wt'].drop_duplicates(['prot_name','peptide','begin', 'mutations', 'HLA']).groupby(
                ['prot_name','peptide','begin', 'mutations', 'Allele Name']).agg({'HLA':('_').join, 'month':'size', 'EL_mark':('_').join,'mut_occurrences':'first'}).reset_index()
            broken = grouped[(grouped['EL_mark'].str.contains('Lost binding'))]
            more1 = grouped[(grouped['EL_mark'].str.contains('Lost binding'))&(grouped['month']>1)]
            more1['EL_mark'] = 'Lost binding'
            more1['check'] = '>2'
            increased = grouped[(grouped['EL_mark'].str.contains('Increased binding'))]
            more1_incr = grouped[(grouped['EL_mark'].str.contains('Increased binding'))&(grouped['month']>1)]
            more1_incr['EL_mark'] = 'Increased binding'
            more1_incr['check'] = '>2'
            tab = pd.merge(tab_short, pd.concat([more1, more1_incr])[['prot_name','peptide', 'mutations', 'Allele Name', 'EL_mark', 'check']],
                           on = ['prot_name','peptide', 'mutations', 'Allele Name'], how = 'left')
            tab['EL_mark'] = [row[2] if row[1] == '>2' else row[0] for row in zip(tab['EL_mark_x'], tab['check'],tab['EL_mark_y'])]
            #print(tab.shape)
            tab = tab.groupby(['prot_name','peptide','begin', 'mutations', 'Allele Name', 'EL_mark', 'month', 'peptide_mut']).agg({'Allele frequency':'first',
                        'mut_occurrences':'first', 'HLA':('_').join, 'fraction':'first', 'wt_EL_Rank':'first',
                        'mut_EL_Rank':'first', 'total_sequences':'first', 'mut_occurrences':'first'}).reset_index()
            tab['Allele frequency'] = tab['Allele frequency'].astype('str')
            tab.to_csv(ds_type+'/Delta_' + ds_type + '_' + name + '_Ranks_RoundedHLA.csv', index = False)
#for the whole gisaid
hla_freq = pd.read_csv('world_hla_alleles.csv', sep = ',')
hla_freq['Allele Name'] = ['HLA-'+i[0] + i[2:4] for i in hla_freq['Allele'].values]
HLA = hla_freq.groupby(['Allele Name']).sum().reset_index(level='Allele Name')

name = 'gisaid'
om_nofreq = pd.read_csv('Omicron_' + name + '_Ranks_WithoutFreqs.csv', index_col = False)
om_nofreq['HLA'] =  om_nofreq['Allele Name']
om_nofreq['Allele Name'] = [i.split(':')[0] for i in om_nofreq['Allele Name'].values]
tab_short = pd.merge(HLA, om_nofreq, on = 'Allele Name', how = 'right').fillna('no_freq')
grouped = tab_short[tab_short['mutations']!='wt'].drop_duplicates(['prot_name','peptide','begin', 'mutations', 'HLA']).groupby(
                ['prot_name','peptide','begin', 'mutations', 'Allele Name']).agg({'HLA':('_').join, 'month':'size', 'EL_mark':('_').join,'mut_occurrences':'first'}).reset_index()
broken = grouped[(grouped['EL_mark'].str.contains('Lost binding'))]
more1 = grouped[(grouped['EL_mark'].str.contains('Lost binding'))&(grouped['month']>1)]
more1['EL_mark'] = 'Lost binding'
more1['check'] = '>2'
increased = grouped[(grouped['EL_mark'].str.contains('Increased binding'))]
more1_incr = grouped[(grouped['EL_mark'].str.contains('Increased binding'))&(grouped['month']>1)]
more1_incr['EL_mark'] = 'Increased binding'
more1_incr['check'] = '>2'
tab = pd.merge(tab_short, pd.concat([more1, more1_incr])[['prot_name','peptide', 'mutations', 'Allele Name', 'EL_mark',
                                        'check']], on = ['prot_name','peptide', 'mutations', 'Allele Name'], how = 'left')
tab['EL_mark'] = [row[2] if row[1] == '>2' else row[0] for row in zip(tab['EL_mark_x'], tab['check'],tab['EL_mark_y'])]
tab = tab.groupby(['prot_name','peptide','begin', 'mutations', 'Allele Name', 'EL_mark', 'month', 'peptide_mut']).agg({'Allele frequency':'first',
                    'mut_occurrences':'first', 'HLA':('_').join, 'fraction':'first', 'wt_EL_Rank':'first', 'mut_EL_Rank':'first', 'total_sequences':'first', 'mut_occurrences':'first'}).reset_index()
tab['Allele frequency'] = tab['Allele frequency'].astype('str')
tab.to_csv('Omicron_' + name + '_Ranks_RoundedHLA.csv', index = False)


d_nofreq = pd.read_csv('Delta_' + name + '_Ranks_WithoutFreqs.csv', index_col = False)
d_nofreq['HLA'] = d_nofreq['Allele Name']
d_nofreq['Allele Name'] = [i.split(':')[0] for i in d_nofreq['Allele Name'].values]
tab_short = pd.merge(HLA, d_nofreq, on = 'Allele Name', how = 'right').fillna('no_freq')
grouped = tab_short[tab_short['mutations']!='wt'].drop_duplicates(['prot_name','peptide','begin', 'mutations', 'HLA']).groupby(
                ['prot_name','peptide','begin', 'mutations', 'Allele Name']).agg({'HLA':('_').join, 'month':'size', 'EL_mark':('_').join,'mut_occurrences':'first'}).reset_index()
broken = grouped[(grouped['EL_mark'].str.contains('Lost binding'))]
more1 = grouped[(grouped['EL_mark'].str.contains('Lost binding'))&(grouped['month']>1)]
more1['EL_mark'] = 'Lost binding'
more1['check'] = '>2'
increased = grouped[(grouped['EL_mark'].str.contains('Increased binding'))]
more1_incr = grouped[(grouped['EL_mark'].str.contains('Increased binding'))&(grouped['month']>1)]
more1_incr['EL_mark'] = 'Increased binding'
more1_incr['check'] = '>2'
tab = pd.merge(tab_short, pd.concat([more1, more1_incr])[['prot_name','peptide', 'mutations', 'Allele Name', 'EL_mark', 'check']],
                           on = ['prot_name','peptide', 'mutations', 'Allele Name'], how = 'left')
tab['EL_mark'] = [row[2] if row[1] == '>2' else row[0] for row in zip(tab['EL_mark_x'], tab['check'],tab['EL_mark_y'])]
            #print(tab.shape)
tab = tab.groupby(['prot_name','peptide','begin', 'mutations', 'Allele Name', 'EL_mark', 'month', 'peptide_mut']).agg({'Allele frequency':'first',
                        'mut_occurrences':'first', 'HLA':('_').join, 'fraction':'first', 'wt_EL_Rank':'first',
                        'mut_EL_Rank':'first', 'total_sequences':'first', 'mut_occurrences':'first'}).reset_index()
tab['Allele frequency'] = tab['Allele frequency'].astype('str')
tab.to_csv('Delta_' + name + '_Ranks_RoundedHLA.csv', index = False)